/**
 * ML Evaluation Result Contract
 * 
 * This file defines the data structure that the ML system MUST return
 * when evaluating student answers. The backend expects this exact shape.
 * 
 * Purpose:
 * - Decouples backend from ML implementation details
 * - Enables ML system to evolve independently
 * - Provides clear contract for validation
 * 
 * Note: This is NOT a Mongoose model - it's a plain JS contract/interface
 */

/**
 * @typedef {Object} QuestionResult
 * @property {string} questionId - MongoDB ObjectId of the question
 * @property {number} aiScore - Score assigned by ML model (0 to maxScore)
 * @property {number} maxScore - Maximum possible score for this question
 * @property {number} confidence - ML confidence level (0.0 to 1.0)
 * @property {string} aiFeedback - Feedback generated by ML
 * @property {string[]} matchedKeypoints - Concepts/keywords student covered
 * @property {string[]} missingKeypoints - Concepts/keywords student missed
 * @property {Object} metadata - Additional ML-specific data (optional)
 */

/**
 * @typedef {Object} MLEvaluationResult
 * @property {QuestionResult[]} results - Array of per-question evaluations
 * @property {number} aiTotalScore - Total score across all questions
 * @property {number} maxTotalScore - Maximum possible total score
 * @property {number} averageConfidence - Average confidence across all questions
 * @property {string} method - ML method used (e.g., 'rubric_based', 'hybrid')
 * @property {Date} evaluatedAt - Timestamp of evaluation
 * @property {Object} systemMetadata - ML system version, runtime info (optional)
 */

/**
 * Validates the structure of a single question result
 * 
 * @param {QuestionResult} result - Question result to validate
 * @returns {Object} { valid: boolean, errors: string[] }
 */
function validateQuestionResult(result) {
  const errors = [];

  // Required fields
  if (!result.questionId) {
    errors.push('questionId is required');
  }

  if (typeof result.aiScore !== 'number') {
    errors.push('aiScore must be a number');
  } else if (result.aiScore < 0) {
    errors.push('aiScore cannot be negative');
  }

  if (typeof result.maxScore !== 'number') {
    errors.push('maxScore must be a number');
  } else if (result.maxScore <= 0) {
    errors.push('maxScore must be positive');
  }

  // Score consistency check
  if (typeof result.aiScore === 'number' && typeof result.maxScore === 'number') {
    if (result.aiScore > result.maxScore) {
      errors.push(`aiScore (${result.aiScore}) cannot exceed maxScore (${result.maxScore})`);
    }
  }

  if (typeof result.confidence !== 'number') {
    errors.push('confidence must be a number');
  } else if (result.confidence < 0 || result.confidence > 1) {
    errors.push('confidence must be between 0.0 and 1.0');
  }

  if (typeof result.aiFeedback !== 'string') {
    errors.push('aiFeedback must be a string');
  }

  if (!Array.isArray(result.matchedKeypoints)) {
    errors.push('matchedKeypoints must be an array');
  }

  if (!Array.isArray(result.missingKeypoints)) {
    errors.push('missingKeypoints must be an array');
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

/**
 * Validates the complete ML evaluation result
 * 
 * @param {MLEvaluationResult} mlResult - Complete evaluation result from ML
 * @returns {Object} { valid: boolean, errors: string[] }
 */
function validateMLEvaluationResult(mlResult) {
  const errors = [];

  // Check top-level structure
  if (!mlResult || typeof mlResult !== 'object') {
    return {
      valid: false,
      errors: ['ML result must be an object']
    };
  }

  // Validate results array
  if (!Array.isArray(mlResult.results)) {
    errors.push('results must be an array');
  } else {
    if (mlResult.results.length === 0) {
      errors.push('results array cannot be empty');
    }

    // Validate each question result
    mlResult.results.forEach((result, index) => {
      const validation = validateQuestionResult(result);
      if (!validation.valid) {
        errors.push(`Question ${index}: ${validation.errors.join(', ')}`);
      }
    });
  }

  // Validate overall scores
  if (typeof mlResult.aiTotalScore !== 'number') {
    errors.push('aiTotalScore must be a number');
  } else if (mlResult.aiTotalScore < 0) {
    errors.push('aiTotalScore cannot be negative');
  }

  if (typeof mlResult.maxTotalScore !== 'number') {
    errors.push('maxTotalScore must be a number');
  } else if (mlResult.maxTotalScore <= 0) {
    errors.push('maxTotalScore must be positive');
  }

  // Total score consistency check
  if (typeof mlResult.aiTotalScore === 'number' && typeof mlResult.maxTotalScore === 'number') {
    if (mlResult.aiTotalScore > mlResult.maxTotalScore) {
      errors.push(`aiTotalScore (${mlResult.aiTotalScore}) cannot exceed maxTotalScore (${mlResult.maxTotalScore})`);
    }
  }

  // Validate average confidence
  if (typeof mlResult.averageConfidence !== 'number') {
    errors.push('averageConfidence must be a number');
  } else if (mlResult.averageConfidence < 0 || mlResult.averageConfidence > 1) {
    errors.push('averageConfidence must be between 0.0 and 1.0');
  }

  // Validate method
  if (typeof mlResult.method !== 'string') {
    errors.push('method must be a string');
  }

  // Validate timestamp
  if (mlResult.evaluatedAt && !(mlResult.evaluatedAt instanceof Date) && isNaN(Date.parse(mlResult.evaluatedAt))) {
    errors.push('evaluatedAt must be a valid date');
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

/**
 * Creates an example ML evaluation result (for testing/documentation)
 * 
 * @returns {MLEvaluationResult} Example result conforming to contract
 */
function createExampleResult() {
  return {
    results: [
      {
        questionId: '507f1f77bcf86cd799439011',
        aiScore: 7.5,
        maxScore: 10,
        confidence: 0.85,
        aiFeedback: 'Good understanding of photosynthesis. Missing details about oxygen production.',
        matchedKeypoints: ['sunlight', 'chlorophyll', 'energy conversion'],
        missingKeypoints: ['oxygen', 'carbon dioxide'],
        metadata: {
          processingTime: 0.234,
          modelVersion: '1.0.0'
        }
      },
      {
        questionId: '507f1f77bcf86cd799439012',
        aiScore: 9.0,
        maxScore: 10,
        confidence: 0.92,
        aiFeedback: 'Excellent explanation of cellular respiration.',
        matchedKeypoints: ['glucose', 'ATP', 'mitochondria', 'oxygen'],
        missingKeypoints: [],
        metadata: {
          processingTime: 0.189,
          modelVersion: '1.0.0'
        }
      }
    ],
    aiTotalScore: 16.5,
    maxTotalScore: 20,
    averageConfidence: 0.885,
    method: 'hybrid_rubric_similarity',
    evaluatedAt: new Date(),
    systemMetadata: {
      mlVersion: '1.0.0',
      pythonVersion: '3.11',
      totalProcessingTime: 0.423
    }
  };
}

module.exports = {
  validateQuestionResult,
  validateMLEvaluationResult,
  createExampleResult
};
